name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          path: 'QFRCDashboard-source'

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV

      - name: Package artifacts properly
        shell: bash
        run: |
          mv ${{ github.workspace }}/QFRCDashboard-source QFRCDashboard-${{ env.VERSION }}
          ls *
          mv QFRCDashboard-Linux-Binary*/QFRCDashboard.tar.gz QFRCDashboard-Linux-Binary-${{ env.VERSION }}.tar.gz
          mv QFRCDashboard-*.AppImage/QFRCDashboard-*.AppImage QFRCDashboard-Linux-${{ env.VERSION }}-x86_64.AppImage
          mv QFRCDashboard-Windows-Setup*/QFRCDashboard* QFRCDashboard-Windows-Setup-${{ env.VERSION }}.exe

          tar xf QFRCDashboard-macOS*/QFRCDashboard.tar.gz

          mv QFRCDashboard*.app QFRCDashboard-macOS-${{ env.VERSION }}.app

          zip -r QFRCDashboard-macOS-${{ env.VERSION }}.zip QFRCDashboard-macOS-${{ env.VERSION }}.app
          
          zip -r QFRCDashboard-Windows-Portable-${{ env.VERSION }}.zip QFRCDashboard-Windows-Portable*/* QFRCDashboard-Windows-Portable-${{ env.VERSION }}.zip

          tar -czf QFRCDashboard-${{ env.VERSION }}.tar.gz QFRCDashboard-${{ env.VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: QFRCDashboard ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: |
            QFRCDashboard-Linux-Binary-${{ env.VERSION }}.tar.gz
            QFRCDashboard-Linux-${{ env.VERSION }}-x86_64.AppImage
            QFRCDashboard-Windows-Portable-${{ env.VERSION }}.zip
            QFRCDashboard-${{ env.VERSION }}.tar.gz
            QFRCDashboard-Windows-Setup-${{ env.VERSION }}.exe
            QFRCDashboard-macOS-${{ env.VERSION }}.zip
