name: Build Application

on: [pull_request, push]
  paths-ignore:
    - '**.md'
    - '**/LICENSE'
    - '.github/ISSUE_TEMPLATE/**'
    - '.markdownlint**'
  workflow_dispatch:

jobs:

  build_debug:
    name: Build Debug
    uses: ./.github/workflows/build.yml
    with:
      build_type: Debug
