name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          path: 'QFRCDashboard-source'

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV

      - name: Package artifacts properly
        shell: bash
        run: |
          mv ${{ github.workspace }}/QFRCDashboard-source QFRCDashboard-${{ env.VERSION }}
          ls
          echo
          echo
          ls *
          echo
          echo

          for arch in amd64 aarch64
          do
            mv QFRCDashboard-Linux-Binary*${arch}/QFRCDashboard.tar.zst QFRCDashboard-Linux-${{ env.VERSION }}-$arch.tar.zst
            mv QFRCDashboard*${arch}.AppImage/*.AppImage QFRCDashboard-Linux-${{ env.VERSION }}-${arch}.AppImage

          done

          # TODO: once windows has arm, move this up
          for arch in amd64
          do
            mv QFRCDashboard-Windows-Setup*${arch}/Dashboard* QFRCDashboard-Windows-Setup-${{ env.VERSION }}-${arch}.exe
            zip -r QFRCDashboard-Windows-Portable-${{ env.VERSION }}-${arch}.zip QFRCDashboard-Windows-Portable*${arch}/*
          done

          tar xf QFRCDashboard-macOS*/QFRCDashboard.tar.gz
          mv *Dashboard*.app QFRCDashboard-macOS-${{ env.VERSION }}.app

          # macOS builds contain both aarch64 and amd64 binaries, meaning the binaries are universal
          zip -r QFRCDashboard-macOS-${{ env.VERSION }}-universal.zip QFRCDashboard-macOS-${{ env.VERSION }}.app

          tar -czf QFRCDashboard-${{ env.VERSION }}.tar.gz QFRCDashboard-${{ env.VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: QFRCDashboard ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: |
            QFRCDashboard-${{ env.VERSION }}.tar.gz

            QFRCDashboard-Linux-${{ env.VERSION }}-amd64.tar.zst
            QFRCDashboard-Linux-${{ env.VERSION }}-aarch64.tar.zst
            QFRCDashboard-Linux-${{ env.VERSION }}-amd64.AppImage
            QFRCDashboard-Linux-${{ env.VERSION }}-aarch64.AppImage

            QFRCDashboard-Windows-Portable-${{ env.VERSION }}-amd64.zip
            QFRCDashboard-Windows-Portable-${{ env.VERSION }}-aarch64.zip
            QFRCDashboard-Windows-Setup-${{ env.VERSION }}-amd64.exe
            QFRCDashboard-Windows-Setup-${{ env.VERSION }}-aarch64.exe

            QFRCDashboard-macOS-${{ env.VERSION }}-universal.zip
